site_name: WCSharp Documentation
site_url: https://mdlsvensson.github.io/WCSharp-docs
theme:
  name: material
  features:
    - search.highlight
    - search.suggest
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    # - navigation.prune
    - toc.follow
  font:
    text: IBM Plex Sans
    code: Fira Code
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: wcsharp
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
